---

# DO NOT RUN MANUALLY - MEANT TO BE RUN FROM TERRAFORM

- name: Add new host to Ansible inventory and Pihole DNS
  hosts: localhost
  gather_facts: false
  connection: local
  become: false

  tasks:

    - name: Create inventory entry
      ini_file:
        dest: ~/code/Ansible/hosts
        section: "{{ group }}"
        option: "{{ newhost }}"
        allow_no_value: yes

    - name: Refresh metadata
      meta: refresh_inventory
    
- name: Add host record to pihole custom.list
  hosts: pihole
  gather_facts: false
  remote_user: eingram
  become: true
  become_method: sudo

  tasks:

    - name: Add record
      lineinfile:
        backup: yes
        path: /etc/pihole/custom.list
        line: "{{ newip }} {{ newhost }}"
        state: present

    - name: Restart pihole-FTL
      service:
        name: pihole-FTL
        state: restarted

- name: Create eingram user
  hosts: "{{newhost}}"
  gather_facts: false
  remote_user: ansible
  become: true
  become_method: sudo

  tasks:

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      user:
        name=eingram
        groups=wheel
        append=yes
        state=present
        createhome=yes

    - name: Set up authorized keys for the deployer user
      authorized_key: user=eingram key="{{item}}"
      with_file:
        - ~/code/Terraform/files/eingram_id_rsa.pub