vsphere_template  = "TMP-Rocky85_Packer_2022_04"
vsphere_datastore = "XN_iSCSI_SSD2"
vsphere_network   = "Lab-LAN1"
vm_folder         = "Terraform Provisioned"
vm_name           = "RockyTest"
ip_address        = "10.10.0.60"
ip_gateway        = "10.10.0.1"
vm_ram            = 4096
vm_cpu            = 2
ansible_group     = "Temp" 