name: Deploy terraform project

on:
  push:
    branches:
      - main
    paths:
      - 'projects/**/**'

jobs:
  deploy:
    name: Deploy Terraform Project
    runs-on: arc-runners
    outputs:
      project: ${{ steps.collect-artifacts.outputs.project }}
      ansible_limit: ${{ steps.collect-artifacts.outputs.ansible_limit }}
    env:
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      GCP_STORAGE: ${{ secrets.GCP_STORAGE }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: eingram-homelab/terraform
          ref: main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          files: |
            projects/**/**/*.tf

      - name: Ensure only one project is changed
        id: check-projects
        run: |
          if [ "${{ steps.changed-files.outputs.all_changed_files }}" != "" ]; then
            echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
            projects=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '([a-zA-Z0-9\-\_]+\/)+')
            echo ${projects[@]}
            unique_project=$(echo "$projects" | sort -u)
            echo $unique_project
            if [ $(echo "$unique_project" | wc -l) -gt 1 ]; then
              echo "Error: More than one project changed. Please limit changes to one project at a time."
              exit 1
            fi
            echo "project=$unique_project" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main
        with:
          terraform_version: 1.11.3

      - name: Create json cred file
        run: |
          echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json

      - name: Generate backend configuration
        run: |
          dir=${{ steps.check-projects.outputs.project }}
          cat > "$dir/backend.tf" <<EOF
          terraform {
            backend "gcs" {
              bucket      = "yc-srv1-tfstate"
              credentials = "/tmp/cred.json"
              prefix      = "terraform/state/$(echo "$dir" | cut -d'/' -f3)-$(basename "$dir")"
            }
          }
          EOF
          echo "Generated backend.tf for $dir"

      - name: Check terraform fmt
        run: |
          dir=${{ steps.check-projects.outputs.project }}
          echo "Running terraform fmt for $dir"
          cd "$dir"
          terraform fmt -check

      - name: Run terraform init
        run: |
          dir=${{ steps.check-projects.outputs.project }}
          echo "Running terraform init for $dir"
          cd "$dir"
          terraform init

      - name: Run terraform validate
        run: |
          dir=${{ steps.check-projects.outputs.project }}
          echo "Running terraform validate for $dir"
          cd "$dir"
          terraform validate

      - name: Run terraform apply
        run: |
          dir=${{ steps.check-projects.outputs.project }}
          echo "Running terraform apply for $dir"
          cd "$dir"
          terraform apply --auto-approve

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Collect artifacts
        id: collect-artifacts
        run: |
          echo "Collecting artifacts from $dir"
          dir=${{ steps.check-projects.outputs.project }}
          echo project_name=$(basename $dir) >> $GITHUB_OUTPUT
          type=$(echo "$dir" | cut -d'/' -f3)
          cd "$dir"
          if [ $type == "vsphere" ]; then
            domain=$(terraform output -json dns_suffix | jq -r '.[0]')
            names=$(terraform output -json name | jq -r '.')
            while IFS= read -r item; do
              name_list+=("$item")
            done < <(jq -c '.[]' <<< "$names")
            for i in "${!name_list[@]}"; do
              name_list[$i]="${name_list[$i]}"."$domain"
            done
            echo ansible_limit="$(IFS=,; echo "${name_list[*]}")" >> $GITHUB_OUTPUT
            echo $GITHUB_OUTPUT

  # call_post_deploy_vsphere_workflow:
  #   needs: deploy
  #   if: needs.deploy.outputs.project == 'vsphere'
  #   uses: eingram-homelab/ansible-col-homelab/.github/workflows/test_reusable.yaml@main
  #   with:
  #     ansible_limit: ${{ needs.deploy.outputs.ansible_limit }}
    


    