---
name: PR Workflow / Terraform

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  flattened-terraform-pr-workflow:
    name: Terraform PR Workflow
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-terraform-pr-workflow.yaml@tf-pr-wf
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref || github.ref_name }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
