---
name: Release Staging Workflow / Terraform

on:
  push:
    branches:
      - test-release-branch
  workflow_dispatch:
    inputs:
      run-id:
        description: "Run ID of the PR Workflow / Terraform run to apply"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  pull-requests: read
  id-token: write
  actions: read

jobs:
  flattened-terraform-release-workflow:
    name: Terraform Release Workflow
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-terraform-release-workflow.yaml@deploy-stg
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      environment: staging
      run-id: ${{ inputs.run-id }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
