---
name: Release Production Workflow / Terraform

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: "Run ID of the PR Workflow / Terraform run to apply"
        required: true
        type: string

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  flattened-terraform-release-workflow:
    name: Terraform Release Workflow
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-terraform-release-workflow.yaml@update-release-workflow
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      environment: production
      run-id: ${{ inputs.run-id }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      GH_TF_TOKEN: ${{ secrets.GH_TF_TOKEN }}
