name: Test reusable workflow

on:
  workflow_call:
    inputs:
      input_var:
        description: 'Input variable from the calling workflow'
        required: true
        type: string

jobs:
  test_job:
    runs-on: arc-runners
    steps:
      - name: Print input variable
        with:
          test_var: ${{ inputs.input_var }}
        run: |
          echo "Input variable from calling workflow: ${{ test_var }}"
