name: Terraform Validate New Template

on:
  workflow_call:
    inputs:
      TMPL_NAME:
        description: 'The VSphere template name'
        required: true
        type: string
    secrets:
      VAULT_TOKEN:
        required: true
      GCP_STORAGE:
        required: true

jobs:
  validate_and_apply:
    name: Validate Packer Templates on vSphere using Terraform
    runs-on: arc-runners
    env:
      TF_VAR_vsphere_template: "${{ inputs.TMPL_NAME }}"
      TF_VAR_vm_name_list: '["gha-vm-test"]'
      TF_VAR_vm_folder_name: "Test"
      TF_VAR_is_windows_image: "${{ contains(inputs.TMPL_NAME, 'Win') && true || false }}"
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: eingram-homelab/terraform
          ref: main

    # When running on self-hosted GitHub Actions runners,
    # NodeJS must be previously installed with the version specified in the action.yml.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main
        with:
          terraform_version: 1.11.3

      - name: Create json cred file
        run: |
          echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json

      - name: Run terraform init
        run: |
          cd projects/vsphere-tmpl-verify
          terraform init

      - name: Run terraform apply
        run: |
          cd projects/vsphere-tmpl-verify
          terraform apply --auto-approve

      - name: Test VM network connectivity
        id: ping
        run: |
          sudo apt-get update && sudo apt-get install -y iputils-ping
          cd projects/vsphere-tmpl-verify
          ping -c 4 "$(terraform output -json default_ip_address | jq -r '.[0]')"
          if [ $? -eq 0 ]; then
            echo "VM is reachable"
          else
            echo "VM is not reachable"
            exit 1
          fi
    
      - name: Destroy Test VM
        if: steps.ping.outcome == 'success'
        run: |
          cd projects/vsphere-tmpl-verify
          terraform destroy --auto-approve
