name: Terraform Validate New Template

on:
  # push:
  #   branches: [ develop ]
  #   paths:
  #     - '**.pkr.hcl'
  # pull_request:
  #   branches: [ develop ]
  #   paths:
  #     - '**.pkr.hcl'
  workflow_dispatch:

jobs:
  validate_and_apply:
    name: Validate Packer Templates on vSphere using Terraform
    runs-on: arc-runners
    env:
      TF_VAR_vsphere_template: "TMP-Rocky9_Packer_RKE2_2025_03_24"
      TF_VAR_vm_name_list: '["linux-test"]'
      TF_VAR_vm_folder_name: "Test"
      TF_VAR_is_windows_image: false
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    # When running on self-hosted GitHub Actions runners,
    # NodeJS must be previously installed with the version specified in the action.yml.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main
        with:
          terraform_version: 1.11.3

      - name: Create json cred file
        run: |
          echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json

      - name: Run terraform init
        run: |
          cd projects/vsphere-tmpl-verify
          terraform init

      - name: Run terraform apply
        run: |
          cd projects/vsphere-tmpl-verify
          terraform apply --auto-approve

      - name: Test VM network connectivity
        id: ping
        run: |
          sudo apt-get update && sudo apt-get install -y iputils-ping
          cd projects/vsphere-tmpl-verify
          ping -c 4 "$(terraform output -json default_ip_address | jq -r '.[0]')"
          if [ $? -eq 0 ]; then
            echo "VM is reachable"
          else
            echo "VM is not reachable"
            exit 1
          fi
      
      - name: Destroy Test VM
        if: steps.ping.outcome == 'success'
        run: |
          cd projects/vsphere-tmpl-verify
          terraform destroy --auto-approve

          